# Generated by Django 4.2.5 on 2023-11-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empleado', models.CharField(max_length=100)),
                ('tiempo_suficiente', models.BooleanField()),
                ('actividades_interesantes', models.BooleanField()),
                ('material_agradable', models.BooleanField()),
                ('trabajo_fuera_aula', models.BooleanField()),
                ('involucrados', models.CharField(choices=[('TODOS', 'TODOS'), ('ALGUNOS', 'ALGUNOS'), ('POCOS', 'POCOS')], max_length=10)),
                ('atentos', models.CharField(choices=[('TODOS', 'TODOS'), ('ALGUNOS', 'ALGUNOS'), ('POCOS', 'POCOS')], max_length=10)),
                ('interrupciones', models.BooleanField()),
                ('influencias', models.TextField()),
                ('situacion_relevante', models.TextField()),
            ],
        ),
    ]
